CREATE TABLE VEICULO
(PLACA    CHAR(7) PRIMARY KEY, 
 COR      VARCHAR(20),
 MODELO   NUMERIC(3) REFERENCES MODELO(COD_MOD),
 PRIORITARIO NUMERIC(8) REFERENCES PROPRIETARIO(COD_PROP),
 ANO_FAB  CHAR(4),
 ANO_MOD  CHAR(4),
 VALOR_SEGURO NUMERIC(9,2));
 
 